language: node_js

before_install:
  - export TZ=Europe/Stockholm

node_js: 
  - "8.10"

#cache:
#  directories:
#    - node_modules

install:
  - "npm install -g typescript"
  - "npm install -g serverless"
  - "npm install"
  - "npm install serverless-webpack --save-dev"

deploy:
  provider: script
  script: bash scripts/deploy.sh
