language: node_js

before_install:
  - export TZ=Europe/Stockholm

node_js: 
  - "8.10"

cache:
  directories:
    - node_modules

install:
  - "npm install -g typescript"
  - "npm install -g serverless"
  - "npm install -g serverless-webpack"
  - "npm install"

deploy:
  provider: script
  script: bash scripts/deploy.sh
