language: node_js

before_install:
- export TZ=Europe/Stockholm

node_js:
- node

cache:
  directories:
    - node_modules

deploy:
  provider: script
  script:
    - npm install -g serverless
    - sls deploy
